spring:
  config:
    import: optional:secrets.yml
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    defer-datasource-initialization: true
logging:
  level:
    org:
      springframework:
      hibernate:
        sql: INFO